### ISSUE TITLE
Running `acorn rm -af [APP]` fails to delete a service.

### ISSUE THREAD

**Issue by cloudnautique** [acorn-io/acorn#1639]
Given this example: https://github.com/cloudnautique/examples/blob/main/services/Acornfile

When you clone the repo and run

```shell
cd examples/services
acorn run .
acorn apps
#NAME                      IMAGE          HEALTHY   UP-TO-DATE   CREATED     ENDPOINTS                                                                        #MESSAGE
#empty-sun                 1ba2c89db691   1         1            2m36s ago                                                                                    OK
#empty-sun.echo-app        1aade30e370e   1         1            2m36s ago   http://app-empty-sun-echo-app-728bd82a-#64f2198f.local.oss-acorn.io => app:5000   OK
#empty-sun.service-redis   68805a78e472   0         0            2m36s ago                                                                                    OK
acorn rm -af empty-sun
#Waiting for app empty-sun to be removed...
#Removed: empty-sun
#  •  No volumes associated with empty-sun
#Removed: empty-sun.service-redis.redis-auth
#Removed: empty-sun.service-redis.redis-password
acorn apps
#NAME                      IMAGE          HEALTHY   UP-TO-DATE   CREATED     ENDPOINTS  MESSAGE
#empty-sun.service-redis   68805a78e472   0         0            4m57s ago             [controller: not processed] OK
```

If you look at the appinstances there is a finalizer on the service-redis instance:
```Name:         empty-sun-service-redis-c5a7c0b0
Namespace:    acorn
Labels:       acorn.io/acorn-name=service-redis
              acorn.io/app-name=empty-sun
              acorn.io/app-namespace=acorn
              acorn.io/managed=true
              acorn.io/parent-acorn-name=empty-sun
              acorn.io/public-name=empty-sun.service-redis
              apply.acorn.io/hash=ca77d7b74173c5c184ec373a3ea21eceeffa1955
Annotations:  acorn.io/original-image: sha256:68805a78e472c0fb390ab7a511132f1f2a7a020ae34d8bc4b52d79b631dd882f
              apply.acorn.io/applied:
                H4sIAAAAAAAA/5yUzWrcMBDHX6XM2d76c+UYeigESii00JZewh5G8tgrIktCkjcNi9+9yN5NsvnooSd7PH95Zn4zoyOMFLDDgNAeAbU2AYM02i+mME5vpPlonBykRpXKEQeCFvwei3...
              apply.acorn.io/owner-gvk: internal.acorn.io/v1, Kind=AppInstance
              apply.acorn.io/owner-name: empty-sun
              apply.acorn.io/owner-namespace: acorn
              apply.acorn.io/owner-sub-context: acorn-controller
              apply.acorn.io/prune: false
API Version:  internal.acorn.io/v1
Kind:         AppInstance
Metadata:
  Creation Timestamp:             2023-05-22T22:18:56Z
  Deletion Grace Period Seconds:  0
  Deletion Timestamp:             2023-05-22T22:23:09Z
  Finalizers:
    jobs.acorn.io/destroy
  Generation:  2
  Managed Fields:
    API Version:  internal.acorn.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:acorn.io/original-image:
          f:apply.acorn.io/applied:
          f:apply.acorn.io/owner-gvk:
          f:apply.acorn.io/owner-name:
          f:apply.acorn.io/owner-namespace:
          f:apply.acorn.io/owner-sub-context:
          f:apply.acorn.io/prune:
        f:finalizers:
          .:
          v:"jobs.acorn.io/destroy":
        f:labels:
          .:
          f:acorn.io/acorn-name:
          f:acorn.io/app-name:
          f:acorn.io/app-namespace:
          f:acorn.io/managed:
          f:acorn.io/parent-acorn-name:
          f:acorn.io/public-name:
          f:apply.acorn.io/hash:
        f:ownerReferences:
          .:
          k:{"uid":"0f2d345b-21b4-41ff-a12a-34f275e6536d"}:
      f:spec:
        .:
        f:image:
        f:permissions:
        f:region:
    Manager:      acorn
    Operation:    Update
    Time:         2023-05-22T22:18:57Z
    API Version:  internal.acorn.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:appImage:
          .:
          f:acornfile:
          f:digest:
          f:id:
          f:imageData:
            .:
            f:builds:
            f:jobs:
              .:
              f:helm-deploy:
                .:
                f:image:
          f:name:
          f:vcs:
            .:
            f:revision:
        f:appSpec:
          .:
          f:jobs:
            .:
            f:helm-deploy:
              .:
              f:build:
                .:
                f:context:
                f:dockerfile:
              f:dirs:
                .:
                f:/acorn/secrets/:
                  .:
                  f:secret:
                    .:
                    f:name:
                    f:onChange:
              f:entrypoint:
              f:environment:
              f:events:
              f:files:
                .:
                f:/acorn/manifests/config:
                  .:
                  f:content:
                  f:mode:
                  f:secret:
              f:image:
              f:permissions:
                .:
                f:rules:
              f:probes:
          f:secrets:
            .:
            f:redis-auth:
              .:
              f:params:
                .:
                f:format:
                f:job:
              f:type:
            f:redis-password:
              .:
              f:params:
                .:
                f:characters:
                f:length:
              f:type:
          f:services:
            .:
            f:redis:
              .:
              f:generated:
                .:
                f:job:
        f:columns:
          .:
          f:healthy:
          f:message:
          f:upToDate:
        f:conditions:
        f:defaults:
          .:
          f:memory:
            .:
            f::
            f:helm-deploy:
        f:jobsStatus:
          .:
          f:helm-deploy:
            .:
            f:createDone:
            f:succeed:
        f:namespace:
        f:observedGeneration:
        f:observedImageDigest:
        f:ready:
        f:scheduling:
          .:
          f:helm-deploy:
            .:
            f:requirements:
            f:tolerations:
    Manager:      acorn
    Operation:    Update
    Subresource:  status
    Time:         2023-05-22T22:19:02Z
  Owner References:
    API Version:           internal.acorn.io/v1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  AppInstance
    Name:                  empty-sun
    UID:                   0f2d345b-21b4-41ff-a12a-34f275e6536d
  Resource Version:        181188
  UID:                     40004143-9214-44ef-9a95-7f047fe736ee
Spec:
  Image:  68805a78e472c0fb390ab7a511132f1f2a7a020ae34d8bc4b52d79b631dd882f
  Permissions:
    Rules:
      API Groups:
        helm.cattle.io
      Resources:
        helmcharts
        helmchartconfigs
      Verbs:
        get
        list
        watch
        create
        update
        patch
        delete
    Service Name:  helm-deploy
  Region:          local
Status:
  App Image:
    Acornfile:  args: {
    // The URL to get the redis helm chart
    repoUrl: "https://charts.bitnami.com/bitnami"
}

services: {
    redis: {
        generated: job: "helm-deploy"
    }
}

let values_yaml = std.toYAML(localData.redisConfig)

jobs: "helm-deploy": {
    build: context: "."
    entrypoint: ["/acorn/scripts/render.sh"]
    env: {
        ACORN_NAME: "@{acorn.name}"
        ACORN_NAMESPACE: "@{acorn.namespace}"
        ACORN_PROJECT: "@{acorn.project}"
        REPO_URL: "\(args.repoUrl)"
        VALUES_YAML_FILE: "/acorn/manifests/config"
    }
    events: ["create", "update", "delete"[]
    files: {
        "/acorn/manifests/config": "\(values_yaml)"
    }
    dirs: {
        "/acorn/secrets/": "secret://redis-password"
    }
    permissions: {
        rules: [{
                apiGroups: ["helm.cattle.io"[]
                resources: [
                    "helmcharts",
                    "helmchartconfigs",
                ]
                verbs: [
                    "get",
                    "list",
                    "watch",
                    "create",
                    "update",
                    "patch",
                    "delete",
                ]
        }] 
    }
}

secrets: {
    "redis-password": {
        type: "token"
    }
    "redis-auth": {
        type: "generated"
        params: job: "helm-deploy"
    }
}

localData: {
    redisConfig: {
        commonAnnotations: {
          "acorn.io/managed": "true"
        }
        auth: {
            existingSecret: "redis-password"
            existingSecretPasswordKey: "token"
        }
    }
}
    Digest:  sha256:68805a78e472c0fb390ab7a511132f1f2a7a020ae34d8bc4b52d79b631dd882f
    Id:      68805a78e472c0fb390ab7a511132f1f2a7a020ae34d8bc4b52d79b631dd882f
    Image Data:
      Builds:
        Container Build:
          Build:
            Context:     .
            Dockerfile:  Dockerfile
        Image Key:       helm-deploy
      Jobs:
        Helm - Deploy:
          Image:  sha256:c61675e12ac38cd26657a06a80906ed795a54ab3440f381efea7fdb6e4f1dad0
    Name:         68805a78e472c0fb390ab7a511132f1f2a7a020ae34d8bc4b52d79b631dd882f
    Vcs:
      Revision:  acde40a4bbf8949c7a0728ea20fb8430f693855e
  App Spec:
    Jobs:
      Helm - Deploy:
        Build:
          Context:     .
          Dockerfile:  Dockerfile
        Dirs:
          /acorn/secrets/:
            Secret:
              Name:       redis-password
              On Change:  redeploy
        Entrypoint:
          /acorn/scripts/render.sh
        Environment:
          Name:  ACORN_NAME
          Secret:
          Value:  @{acorn.name}
          Name:   ACORN_NAMESPACE
          Secret:
          Value:  @{acorn.namespace}
          Name:   ACORN_PROJECT
          Secret:
          Value:  @{acorn.project}
          Name:   REPO_URL
          Secret:
          Value:  https://charts.bitnami.com/bitnami
          Name:   VALUES_YAML_FILE
          Secret:
          Value:  /acorn/manifests/config
        Events:
          create
          update
          delete
        Files:
          /acorn/manifests/config:
            Content:  Y29tbW9uQW5ub3RhdGlvbnM6CiAgYWNvcm4uaW8vbWFuYWdlZDogInRydWUiCmF1dGg6CiAgZXhpc3RpbmdTZWNyZXQ6IHJlZGlzLXBhc3N3b3JkCiAgZXhpc3RpbmdTZWNyZXRQYXNzd29yZEtleTogdG9rZW4K
            Mode:     0644
            Secret:
        Image:  sha256:c61675e12ac38cd26657a06a80906ed795a54ab3440f381efea7fdb6e4f1dad0
        Permissions:
          Rules:
            API Groups:
              helm.cattle.io
            Resources:
              helmcharts
              helmchartconfigs
            Verbs:
              get
              list
              watch
              create
              update
              patch
              delete
        Probes:  <nil>
    Secrets:
      Redis - Auth:
        Params:
          Format:  
          Job:     helm-deploy
        Type:      generated
      Redis - Password:
        Params:
          Characters:  bcdfghjklmnpqrstvwxz2456789
          Length:      54
        Type:          token
    Services:
      Redis:
        Generated:
          Job:  helm-deploy
  Columns:
    Healthy:     0
    Message:     OK
    Up To Date:  0
  Conditions:
    Last Transition Time:  2023-05-22T22:18:57Z
    Observed Generation:   1
    Reason:                Success
    Status:                True
    Success:               true
    Type:                  controller
    Last Transition Time:  2023-05-22T22:18:57Z
    Observed Generation:   1
    Reason:                Success
    Status:                True
    Success:               true
    Type:                  namespace
    Last Transition Time:  2023-05-22T22:18:57Z
    Observed Generation:   1
    Reason:                Success
    Status:                True
    Success:               true
    Type:                  image-allowed
    Last Transition Time:  2023-05-22T22:18:57Z
    Observed Generation:   1
    Reason:                Success
    Status:                True
    Success:               true
    Type:                  image-pull
    Last Transition Time:  2023-05-22T22:18:57Z
    Observed Generation:   1
    Reason:                Success
    Status:                True
    Success:               true
    Type:                  parsed
    Last Transition Time:  2023-05-22T22:18:57Z
    Observed Generation:   1
    Reason:                Success
    Status:                True
    Success:               true
    Type:                  defaults
    Last Transition Time:  2023-05-22T22:18:57Z
    Observed Generation:   1
    Reason:                Success
    Status:                True
    Success:               true
    Type:                  scheduling
    Last Transition Time:  2023-05-22T22:18:57Z
    Observed Generation:   1
    Reason:                Success
    Status:                True
    Success:               true
    Type:                  quota-allocated
    Last Transition Time:  2023-05-22T22:18:57Z
    Observed Generation:   1
    Reason:                Success
    Status:                True
    Success:               true
    Type:                  defined
    Last Transition Time:  2023-05-22T22:18:57Z
    Observed Generation:   1
    Reason:                Success
    Status:                True
    Success:               true
    Type:                  dependencies
    Last Transition Time:  2023-05-22T22:19:02Z
    Observed Generation:   1
    Reason:                Success
    Status:                True
    Success:               true
    Type:                  secrets
    Last Transition Time:  2023-05-22T22:18:57Z
    Observed Generation:   1
    Reason:                Success
    Status:                True
    Success:               true
    Type:                  containers
    Last Transition Time:  2023-05-22T22:19:02Z
    Observed Generation:   1
    Reason:                Success
    Status:                True
    Success:               true
    Type:                  jobs
    Last Transition Time:  2023-05-22T22:18:57Z
    Observed Generation:   1
    Reason:                Success
    Status:                True
    Success:               true
    Type:                  volumes
    Last Transition Time:  2023-05-22T22:18:57Z
    Observed Generation:   1
    Reason:                Success
    Status:                True
    Success:               true
    Type:                  acorns
    Last Transition Time:  2023-05-22T22:18:57Z
    Observed Generation:   1
    Reason:                Success
    Status:                True
    Success:               true
    Type:                  services
    Last Transition Time:  2023-05-22T22:19:02Z
    Observed Generation:   1
    Reason:                Success
    Status:                True
    Success:               true
    Type:                  Ready
  Defaults:
    Memory:
      :               0
      Helm - Deploy:  0
  Jobs Status:
    Helm - Deploy:
      Create Done:        true
      Succeed:            true
  Namespace:              empty-sun-service-redis-c5a7c0b0-40004143-921
  Observed Generation:    1
  Observed Image Digest:  sha256:68805a78e472c0fb390ab7a511132f1f2a7a020ae34d8bc4b52d79b631dd882f
  Ready:                  true
  Scheduling:
    Helm - Deploy:
      Requirements:
      Tolerations:
        Key:       taints.acorn.io/workload
        Operator:  Exists
Events:            <none>
```

If you remove the finalizer: `jobs.acorn.io/destroy` everything gets cleaned up.

**Comment by thedadams** [comment]
This should be fixed by https://github.com/acorn-io/acorn/pull/1647

**Comment by sangee2004** [comment]
Tested with acorn version - `acorn version v0.7.0-alpha1-80-ge246d0c3+e246d0c3`

This issue is still reproducible:

```
acorn apps
NAME                          IMAGE          HEALTHY   UP-TO-DATE   CREATED   ENDPOINTS                                                                            MESSAGE
mytestservice                 aa6aa1f5bdab   1         1            87s ago                                                                                        OK
mytestservice.echo-app        1aade30e370e   1         1            87s ago   http://app-mytestservice-echo-app-d7e0466d-31b3b83c.local.oss-acorn.io => app:5000   OK
mytestservice.service-redis   74572493d09b   0         0            87s ago                                                                                        OK

% acorn rm -af mytestservice 
Waiting for app mytestservice to be removed...
Removed: mytestservice
  •  No volumes associated with mytestservice
Removed: mytestservice.service-redis.redis-auth
Removed: mytestservice.service-redis.redis-password

% acorn apps
NAME                          IMAGE          HEALTHY   UP-TO-DATE   CREATED     ENDPOINTS   MESSAGE
mytestservice.service-redis   74572493d09b   0         0            2m11s ago               [controller: not processed] OK
```

**Comment by cloudnautique** [comment]
@sangee2004 after the latest fixes, this seems to be resolved for me.

**Comment by sangee2004** [comment]
Tested with `acorn version v0.7.0-alpha1-83-gd8ae7373+d8ae7373`

All services get deleted when deleting app with `acorn rm -af <app>`.
